"use client";
import { useState } from "react";
import { currency, summarize, type Customer, type Invoice } from "@/src/lib/credit";
import { Icon } from "./ui-icon";
export function AIInsightCard({ customers, invoices, today, onAsk, unavailable }: { customers: Customer[]; invoices: Invoice[]; today: string; onAsk: () => void; unavailable?: boolean }) {
  const data = summarize(customers, invoices, today);
  return <section className="card flex h-full flex-col overflow-hidden"><div className="flex items-center gap-2.5 border-b border-slate-100 px-6 py-5"><span className="text-blue-600"><Icon name="sparkles" /></span><h2 className="section-title">AI Credit Insights</h2><span className="ml-auto rounded bg-blue-50 px-2 py-1 text-[9px] font-medium text-blue-600">PREVIEW</span></div><div className="flex flex-1 flex-col p-6"><p className="text-xs text-slate-400">A little clarity for your next move.</p><dl className="insight-stats"><div><dt>Customers requiring attention</dt><dd>{unavailable ? "—" : <span className="status-badge tone-amber">{data.attention.length} customers</span>}</dd></div><div><dt>Highest-risk customer</dt><dd>{unavailable ? "—" : data.highest?.name ?? "None identified"}</dd></div><div><dt>Total overdue amount</dt><dd className="!text-rose-600">{unavailable ? "—" : currency(data.totalOverdue)}</dd></div></dl><div className="insight-preview"><Icon name="sparkles" className="!h-4 !w-4 text-blue-500" /><p>{unavailable ? "Reconnect your data to see a credit summary." : data.highest ? `Start with ${data.highest.name}. ${data.attention.length} customers need attention, with ${currency(data.totalOverdue)} overdue across your portfolio. Review overdue invoices before extending further credit.` : "No customers currently require attention. Keep an eye on upcoming due dates to stay ahead of collections."}</p></div><p className="mt-2 text-[10px] text-slate-400">Data-based preview · AI generation coming soon</p><button onClick={onAsk} className="primary-button mt-5 w-full justify-center"><Icon name="sparkles" className="!h-4 !w-4" />Ask AI<Icon name="arrow" className="ml-auto !h-4 !w-4" /></button><div className="mt-4 flex items-center justify-center gap-3 text-[10px] text-slate-400"><span>Ask by text</span><span>·</span><Icon name="mic" className="!h-3.5 !w-3.5" /><span>Voice coming soon</span></div></div></section>;
}
export function Assistant({ customers, invoices, today, unavailable }: { customers: Customer[]; invoices: Invoice[]; today: string; unavailable?: boolean }) {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const data = summarize(customers, invoices, today);
  function ask(text: string) {
    setQuestion(text);
    if (unavailable) { setAnswer("Credit data is unavailable. Reconnect to Supabase and refresh before requesting a summary."); return; }
    if (/risk|attention|customer/i.test(text)) setAnswer(`${data.attention.length} customers require attention. ${data.highest ? `The highest-risk customer is ${data.highest.name}.` : "No elevated customer risk is recorded."}`);
    else if (/due soon|upcoming/i.test(text)) setAnswer(`${data.dueSoon.length} invoices totaling ${currency(data.dueSoon.reduce((v, i) => v + Number(i.amount), 0))} are due in the next 7 days, including today.`);
    else if (/overdue|outstanding|summary|credit/i.test(text)) setAnswer(`Total outstanding is ${currency(data.total)}. Of this, ${currency(data.totalOverdue)} is overdue across ${data.overdue.length} invoices.`);
    else setAnswer("This preview supports questions about outstanding balances, overdue invoices, upcoming due dates, and customer risk. Open-ended AI answers will be available when an AI provider is connected.");
  }
  return <section className="card mx-auto max-w-3xl p-6 sm:p-10"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Icon name="sparkles" className="!h-7 !w-7" /></div><h2 className="mt-5 text-center text-xl font-semibold">Your credit, in conversation.</h2><p className="mx-auto mt-2 max-w-md text-center text-sm leading-6 text-slate-500">Ask about balances, upcoming payments, or customers who need your attention.</p><div className="my-7 flex flex-wrap justify-center gap-2">{["Who needs attention?", "What is overdue?", "What is due soon?"].map(q => <button key={q} className="secondary-button text-xs" onClick={() => ask(q)}>{q}</button>)}</div><form onSubmit={e => { e.preventDefault(); if (question.trim()) ask(question); }}><label htmlFor="question" className="mb-2 block text-xs font-medium">Ask a question</label><div className="flex items-center gap-2 rounded-lg border border-slate-200 p-2"><input id="question" className="min-w-0 flex-1 px-2 py-2 text-sm outline-none" placeholder="What should I focus on today?" value={question} onChange={e => setQuestion(e.target.value)} /><button type="button" className="icon-button" disabled aria-label="Microphone — coming soon" title="Voice input coming soon"><Icon name="mic" /></button><button className="primary-button" disabled={!question.trim()} aria-label="Send question"><Icon name="arrow" /></button></div></form>{answer && <div aria-live="polite" className="mt-5 rounded-lg bg-blue-50 p-5 text-sm leading-7 text-slate-700">{answer}</div>}<div className="mt-5 flex items-center justify-between gap-3 text-[11px] text-slate-400"><p>Data-based answers · AI integration coming soon</p><button disabled className="icon-button" aria-label="Play voice response — coming soon" title="Voice responses coming soon"><Icon name="speaker" /></button></div><p className="text-[11px] text-slate-400">Text preview available. Microphone and spoken responses are prepared for a future voice integration.</p></section>;
}

